### ISSUE TITLE
error.. Windows 2012 R2, Exchange 2013 CU10

### ISSUE THREAD

**Issue by mrenergy99** [cunninghamp/ExchangeAnalyzer#42] opened 2016-01-16 02:19 UTC
Getting the following error when running:

 WARNING: Could not load file or assembly 'Microsoft.Exchange.Data, Version=14.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by cunninghamp** [comment] 2016-01-16 03:45
Can you please describe your Exchange environment? How many servers, which versions, any DAGs present, etc?

**Comment by cunninghamp** [comment] 2016-01-16 03:52
My own testing indicates that the cause of this is the use of Get-DatabaseAvailabilityGroup with the -Status switch when an Exchange 2010 DAG is present.

If that is consistent with @mrenergy99 and other reports the fix will be removing -Status from that line and we'll query DAG status later for tests that need it, and only query 2013/2016 DAGs.

**Comment by mrenergy99** [comment] 2016-01-16 04:25
Yes I have an Exchange 2010 DAG in place, removing the -Status switch resolved the issue.

Thank you...

**Comment by cunninghamp** [comment] 2016-01-16 04:50
Fixed has been merged to development branch for next release.

**Closed by cunninghamp** 2016-01-16 04:50 UTC
Labels: bug
